/***********************************************************************
Name: AntiFraudResult
Function：在检查防欺诈时候用于存储欺诈黑名单
***************************************************
History
--------
VERSION     AUTHOR              DATE            DETAIL
1.0         Claudia          2016-11-16        Created
**************************************************************/
global class AntiFraudMessage{
        public String strName { get;set; }
        public String strDesc { get;set; }
}