public with sharing class CSC_Entitlment_ContractOOS {
    public String oOSKey;
    public String oOSType;
    public String serialNumber;
    public String targetQuantity;
    public String oOSGroupID;
    public String productID;
	public String productDescription;
	public String productLineCode;
	public String productLineDescription;
	public String endOfSupportLife;
    public String functionLocation;
    public String oOSCategory;
}