/************************************************************************
* Name: CSC_SNR_Manufactured_BOM
* Purpose: 
* SNR Actual Components in Product Unit 
* Author: Zhou,Xiong
* Create Date: 2016-06-04
***************************************************************************/
public with sharing class CSC_SNR_Manufactured_BOM {
    public CSC_SNR_Manufactured_BOM() {
        
    }

    public String partNumber;
    public String partDescription;
    public String partQty;
}