/************************************************************************
* Name: CSC_SNR_Support_BOM
* Purpose: 
* SNR Support Part Translation
* Author: Zhou,Xiong
* Create Date: 2016-06-04
***************************************************************************/
public with sharing class CSC_SNR_Support_BOM {

    public String partNumber;
    public String sparePartNo;
    public String sparePartDesc;
    public String category;
    public String roHSCode;

}