/***********************************************************************
Name: CSC_CaseEditController
***************************************************
History
--------
VERSION     AUTHOR              DATE            DETAIL
1.0         xuxiangguo          2016-4-21       Created
**************************************************************/
global class CSC_ProductListController {

	/*public String strSN { get; set;}

	public String strProductId { get; set;}

	public String strGetEntitlementInfo { get; set;}

    public CSC_ProductListController() {

    }

    public PageReference getEntitlementInfo () {

    	Date searchDate = Date.today();

    	strGetEntitlementInfo = CSC_SearchEntitlementInfo.getEntitlementInfo('USHA066371', strProductId, searchDate);
        //strGetEntitlementInfo = CSC_SearchEntitlementInfo.getEntitlementInfo(strSN, strProductId, searchDate);

    	return null;
    }*/

}