public with sharing class CSC_Entitlement_EntitlementBySnRequest {
    public CSC_Entitlement_EntitlementBySnRequest() {
        
    }

    public String dataEntrySite;
    public String sourceCustomerID;
    public String redAccessID;
    public String activeContractsOnly;
    public String activeServicesOnly;
	public String includeAddresses;
	public String includeContacts;
	public String includeOffers;
	public String includeDeliverables;
	public String includeModifiers;
	public String includeWorkings;
	public String entitlementCheckDate;
	public String isoCountryCd;
	public String includeManufacturerInfo;
	public String activeWarrantyOnly;
	public String serviceID;
	public String consumerBusinessLogicNeeded;
	public String contractIdentifier;
	public String includeWarranty;
	public String includeContracts;
	public String includeServiceNotes;
	public String warrantySourceSystem;
	public String serialNumber;
	public String productID;
	public String includeCATS;
	public String includePartLevelWarranty;
	public String includeCustomerIdentificationInformation;
}