/***********************************************************************
Name: RplResult
Function：在检查腐败时候存储腐败怀疑黑名单
***************************************************
History
--------
VERSION     AUTHOR              DATE            DETAIL
1.0         Claudia          2016-11-16        Created
**************************************************************/
global class RplMessage{
        public String strName { get;set; }
        public String strAddress { get;set; }
        public String strType { get;set; }
}